### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by dogshep** [Phanx/LibResInfo#3]
Message: ...Ons\LibResInfo-1.0\LibResInfo-1.0\LibResInfo-1.0.lua:227: Usage: UnitDebuff("unit", [index] or ["name", "rank"][, "filter"])
Time: 07/20/16 18:50:08
Count: 5
Stack: (tail call): ?
[C]: in function `UnitDebuff'
...Ons\LibResInfo-1.0\LibResInfo-1.0\LibResInfo-1.0.lua:227: in function `UnitHasIncomingRes'
Interface\AddOns\Grid\Statuses\Resurrect.lua:159: in function `UpdateUnit'
Interface\AddOns\Grid\Statuses\Resurrect.lua:139: in function `?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `SendMessage'
Interface\AddOns\Grid\Roster.lua:248: in function `?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua:120: in function <Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by Phanx** [comment]
This is caused by #2
